modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/aurilisdev/Voltaic/issues" 

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/aurilisdev/Voltaic"

logoFile="voltaic.png"

credits="Thanks to all contributors."

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[mixins]]

config="${mod_id}.mixins.json"

[[accessTransformers]]

file="META-INF/accesstransformer.cfg"