modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/aurilisdev/Electrodynamics/issues" 

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/aurilisdev/Electrodynamics"

logoFile="electrodynamics.png"

credits="Thanks to all contributors. Roi Pasteque, FITFC, Quarkrus, JSBurger, 9thCore, goshante."

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[mixins]]

config="${mod_id}.mixins.json"

[[accessTransformers]]

file="META-INF/accesstransformer.cfg"